library(moments)

statistic <- function(foresty){ 
  
  median(foresty$X)
  median(foresty$Y)
  median(foresty$month)
  median(foresty$day)
  median(foresty$FFMC)
  median(foresty$DMC)
  median(foresty$DC)
  median(foresty$ISI)
  median(foresty$temp)
  median(foresty$RH)
  median(foresty$wind)
  median(foresty$rain)
  median(foresty$area)
  
  mean(foresty$X)
  mean(foresty$Y)
  mean(foresty$FFMC)
  mean(foresty$DMC)
  mean(foresty$DC)
  mean(foresty$ISI)
  mean(foresty$temp)
  mean(foresty$RH)
  mean(foresty$wind)
  mean(foresty$rain)
  mean(foresty$area)
  
  skewness(foresty$X)
  skewness(foresty$Y)
  skewness(foresty$FFMC)
  skewness(foresty$DMC)
  skewness(foresty$DC)
  skewness(foresty$ISI)
  skewness(foresty$temp)
  skewness(foresty$RH)
  skewness(foresty$wind)
  skewness(foresty$rain)
  skewness(foresty$area)
  
  kurtosis(forestya$X)
  kurtosis(foresty$Y)
  kurtosis(foresty$FFMC)
  kurtosis(foresty$DMC)
  kurtosis(foresty$DC)
  kurtosis(foresty$ISI)
  kurtosis(foresty$temp)
  kurtosis(foresty$RH)
  kurtosis(foresty$wind)
  kurtosis(foresty$rain)
  kurtosis(foresty$area)
}